"""The people in state.json, and keeping them out of a public repository.

This file guards three properties, and the order matters because they fail in
opposite directions.

  1. NOTHING IS LOST. The state file is the only record of who has been
     written to. Sealing and unsealing has to return exactly what went in,
     down to the type of every value, or the machine has been given a subtly
     different history to reason about.

  2. NOTHING LEAKS. The whole reason this exists. A field list that misses a
     container looks like it is working - the file is full of ciphertext and
     nobody counts what is still in the clear. So the test counts.

  3. A MISSING KEY STOPS THE RUN. The dangerous failure is not an exception,
     it is a state read with the contacts silently absent, which looks exactly
     like a machine that has never written to anybody and would write to all
     135 employers again.
"""

import copy
import json
import os
import re
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import personal  # noqa: E402

EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
PHONE = re.compile(r"\b(?:0\d{9,10}|\+44\d{9,10})\b")

# A Message-ID is routing metadata generated by a mail server, not a person's
# address. They survive sealing because they are dictionary KEYS in `inbox`
# rather than values, and they are not contact details.
INFRASTRUCTURE = re.compile(
    r"(amazonses|sparkpost|sendgrid|mailgun|PROD\.OUTLOOK\.COM|mta[0-9]|"
    r"\.prd\.|sfdc\.net|firefishsoftware|_mkt_prod)", re.I)


def a_state():
    """A small state with a person in every container that holds one."""
    return {
        "jobs": {
            "adzuna_1": {
                "company": "Kestrel Foods", "status": "replied", "score": 8,
                "contact_email": "fiona.menzies@kestrelfoods.example",
                "contact_phone": "01224123456",
                "contact_name": "Fiona Menzies",
                "sent_to": "fiona.menzies@kestrelfoods.example",
                "sent_body": "Morning Fiona, ...",
                "description": "Apply to hr@kestrelfoods.example on 07700900123",
                "other_contacts": [{"email": "bob@kestrelfoods.example"}],
            },
            "adzuna_2": {"company": "Nothing Ltd", "status": "no_email"},
        },
        "companies_contacted": {
            "kestrel foods": {"email": "fiona.menzies@kestrelfoods.example",
                              "at": "2026-09-01T09:00:00+00:00"},
        },
        "contact_numbers": {
            "ex mil": {"name": "Jean-Claude Hedouin",
                       "numbers": ["+443332026500"], "source": "jc@ex-mil.example"},
        },
        # Keyed by Message-ID, which is what a real inbox is keyed by and
        # what survives sealing. Hex, because real ones are.
        "inbox": {"<4ec6129123da4f829d06f539149da381@mail.example>":
                  {"address": "jane@other.example",
                   "who": "Jane", "subject": "Re: role", "at": 123}},
        "send_counts": {"2026-09-01": 4},
    }


class TestNothingIsLost(unittest.TestCase):
    def setUp(self):
        self.key = personal.make_key()

    def test_a_round_trip_returns_exactly_what_went_in(self):
        before = a_state()
        sealed = personal.seal(copy.deepcopy(before), self.key)
        self.assertEqual(personal.unseal(sealed, self.key), before)

    def test_types_survive(self):
        """A list of phone numbers must come back a list, not its repr."""
        sealed = personal.seal(a_state(), self.key)
        back = personal.unseal(sealed, self.key)
        self.assertIsInstance(back["contact_numbers"]["ex mil"]["numbers"], list)
        self.assertIsInstance(back["jobs"]["adzuna_1"]["other_contacts"], list)

    def test_what_the_machine_matches_on_is_left_alone(self):
        """Company names, statuses and scores are how the machine decides who
        has been written to. Sealing one of those would read as a machine
        that had forgotten every employer."""
        sealed = personal.seal(a_state(), self.key)
        job = sealed["jobs"]["adzuna_1"]
        self.assertEqual(job["company"], "Kestrel Foods")
        self.assertEqual(job["status"], "replied")
        self.assertEqual(job["score"], 8)
        self.assertEqual(sealed["send_counts"], {"2026-09-01": 4})
        self.assertIn("kestrel foods", sealed["companies_contacted"])

    def test_sealing_twice_changes_nothing(self):
        """save() runs on every write and the file is already sealed. A
        second pass must not double-encrypt."""
        once = personal.seal(a_state(), self.key)
        twice = personal.seal(copy.deepcopy(once), self.key)
        self.assertEqual(once, twice)

    def test_the_same_value_always_seals_to_the_same_bytes(self):
        """Determinism is what keeps git deltas working. Randomised
        encryption would rewrite all 18MB on every commit."""
        a = json.dumps(personal.seal(a_state(), self.key), sort_keys=True)
        b = json.dumps(personal.seal(a_state(), self.key), sort_keys=True)
        self.assertEqual(a, b)


class TestNothingLeaks(unittest.TestCase):
    def leftovers(self, blob):
        """Addresses still in the clear, minus mail-server routing metadata.

        A local part of sixteen or more hex characters is a Message-ID, not a
        mailbox - no person has one, and they survive sealing because they
        are dictionary KEYS in `inbox` rather than values."""
        found = set(EMAIL.findall(blob))
        return sorted(a for a in found
                      if not INFRASTRUCTURE.search(a)
                      and not re.match(r"^[0-9a-fA-F]{16,}@", a))

    def test_no_address_or_number_survives_in_the_fixture(self):
        blob = json.dumps(personal.seal(a_state(), personal.make_key()))
        self.assertEqual(self.leftovers(blob), [])
        self.assertEqual(sorted(set(PHONE.findall(blob))), [])

    def test_the_real_state_file_seals_clean(self):
        """The check that actually matters, against the real thing. A field
        list that misses a container looks like it is working, because the
        file is full of ciphertext and nobody counts the remainder. This
        counts. It found `companies_contacted` holding 277 addresses after
        the first version looked finished."""
        path = os.path.join(ROOT, "data", "state.json")
        if not os.path.exists(path):
            self.skipTest("no state file in this checkout")
        with open(path) as f:
            state = json.load(f)
        blob = json.dumps(personal.seal(state, personal.make_key()))
        left = self.leftovers(blob)
        self.assertEqual(left, [], f"{len(left)} addresses still in the clear")
        self.assertEqual(sorted(set(PHONE.findall(blob))), [])


    def test_what_does_survive_is_named_rather_than_filtered_quietly(self):
        """Sealing leaves the `inbox` dictionary KEYS in the clear, because
        they are keys and not values. They are Message-IDs - routing metadata
        a mail server generated - so they are not contact details, but they do
        reveal which mail provider an employer uses.

        Written down as a test rather than left to the filter above, because a
        residue nobody has named is a residue nobody re-examines when the
        threat model changes."""
        sealed = personal.seal(a_state(), personal.make_key())
        keys = list(sealed["inbox"])
        self.assertEqual(len(keys), 1)
        self.assertRegex(keys[0], r"^<[0-9a-fA-F]{16,}@")
        # and the values under it are gone
        self.assertTrue(sealed["inbox"][keys[0]]["address"].startswith(
            personal.MARKER))


class TestAMissingKeyStopsTheRun(unittest.TestCase):
    def test_reading_sealed_state_without_a_key_raises(self):
        """The whole safety property. Returning a state with the contacts
        missing would look exactly like a machine that has written to
        nobody, and the next run would write to all 135 employers again."""
        sealed = personal.seal(a_state(), personal.make_key())
        old = os.environ.pop(personal.KEY_ENV, None)
        try:
            with self.assertRaises(personal.KeyMissing):
                personal.unseal(sealed)
        finally:
            if old is not None:
                os.environ[personal.KEY_ENV] = old

    def test_the_wrong_key_raises_rather_than_returning_rubbish(self):
        sealed = personal.seal(a_state(), personal.make_key())
        with self.assertRaises(Exception):
            personal.unseal(sealed, personal.make_key())

    def test_unsealed_state_needs_no_key(self):
        """Before the first sealed run the file is plaintext, and the machine
        has to keep working."""
        self.assertEqual(personal.unseal(a_state()), a_state())

    def test_writing_without_a_key_is_allowed(self):
        """Local work on a machine where the file never leaves. The loud
        failure belongs on the read side, not here."""
        old = os.environ.pop(personal.KEY_ENV, None)
        try:
            self.assertEqual(personal.seal(a_state()), a_state())
        finally:
            if old is not None:
                os.environ[personal.KEY_ENV] = old


if __name__ == "__main__":
    unittest.main()
